# Test config file for Blip
module:
  module_name:  'blank_config'
  module_type:  ['data']
  module_mode:  ['arrakis']
  gpu:          True
  gpu_device:   0
  verbose:      False

dataset:
  # ---- Arrakis ----
  # This section defines the 'arrakis.py' submodule which takes in
  # outputs from different Arrakis iterations and constructs a common dataset format
  # in .npz or .hdf5 files.
  # If this is the first time processing the simulation output
  process_simulation: True
  simulation_type:    'LArSoft'
  simulation_folder:  "~/data/"
  simulation_files:   ["labeling_sim_arrakis.root"]