# Test config file for Blip
module:
  module_type:  'training'
  gpu:          True
  gpu_device:   0

dataset:
  # If this is the first time processing the simulation output
  process_simulation: False
  simulation_folder:  ""
  simulation_files:   []

  # Otherwise, we want to just load the resulting data
  dataset_type:   ""
  dataset_folder: ""
  dataset_files:  []

  positions:  []
  features:   []
  classes:    []
  clusters:   []
  
  # We only want to cluster shapes which are blips
  class_mask: ""
  label_mask: ""

  # clustering related parameters
  dbscan_min_samples: 6
  dbscan_eps:         10.0
  cluster_positions:  []

  # we can regroup classes to reduce their number,
  # e.g., say we want to train so that there are
  # only two important shapes, "blip" and "not-blip",
  # then we would consolidate like below:
  consolidate_classes:  
  #   shape:  [["blip"], [""]]
  
  sample_weights: []
  class_weights:  []
  normalized:     False
  root:           "."
  skip_processing:  False
  transform:      null
  pre_transform:  null
  pre_filter:     null

loader:
  batch_size:       32
  test_split:       0.1
  test_seed:        100
  validation_split: 0.2
  validation_seed:  101
  num_workers:      4
  sparse:           True

training:
  epochs:       2
  checkpoint:   10
  progress_bar: 'all'   # train, validation, test, all
  rewrite_bar:  False   # wether to leave bars after each epoch
  save_predictions: True  # wether to save network outputs in original file
  no_timing:  False     # wether to keep timing/memory info in callback
  seed:       42

model:
  
criterion:
  
metrics:
  
callbacks:
  
optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9