from .generic_loss import *
from .angular_loss import *
from .binary_cross_entropy_loss import *
from .contrastive_loss import *
from .cross_entropy_loss import *
from .dice_loss import *
from .focal_loss import *
from .jaccard_index_loss import *
from .l1_loss import *
from .l2_loss import *
from .nll_loss import *
from .ntx_entropy_loss import *
from .prob_loss import *
from .tversky_loss import *
from .loss_handler import *