# Test config file for Blip
dataset:
  # If this is the first time processing the simulation output
  process_simulation: True
  simulation_files:   ["data/arrakis_output_1.root"]
  # Otherwise, we want to just load the resulting data
  dataset_type:   "wire_plane"
  dataset_files:  ["data/blip_simulation_0/point_cloud_view0_tpc0.npz"]

loader:
  batch_size:       2
  test_split:       0.0
  test_seed:        100
  validation_split: 0.2
  validation_seed:  100
  num_workers:      4

model:
  model_type:   "PointNet++"
  set_abstraction_layers:
    sampling_methods:       ["farthest_point"]
    sampling_num_samples:   [256]
    grouping_methods:       ["query_ball_point"]
    grouping_type:          ["multi-scale"]
    grouping_radii:         [[2, 4, 8]]
    grouping_samples:       [[16, 32, 128]]
    pointnet_embedding_type:        ["dynamic_edge_conv", "dynamic_edge_conv", "dynamic_edge_conv"]
    pointnet_embedding_mlp_layers:  [[2,2],[2,2],[2,2]]
    pointnet_number_of_neighbors:   [20, 20, 20]
    pointnet_aggregation:           ["max", "max", "max"]
    pointnet_input_dimension:       [3]
  segmentation_layers:
  classification_layers:

optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9

criterion:
metrics:
callbacks:
training: