# Test config file for Blip
dataset:
  # If this is the first time processing the simulation output
  process_simulation: True
  simulation_files:   [
    "data/protodune_mc_0.root",
    "data/protodune_mc_1.root",
    "data/protodune_mc_2.root",
    "data/protodune_mc_3.root",
    "data/protodune_mc_4.root"
  ]

  # Otherwise, we want to just load the resulting data
  dataset_type:   "wire_plane"
  dataset_files:  [
    "data/blip_simulation_0/point_cloud_view0_tpc0.npz",
    "data/blip_simulation_1/point_cloud_view0_tpc0.npz",
    "data/blip_simulation_2/point_cloud_view0_tpc0.npz",
    "data/blip_simulation_3/point_cloud_view0_tpc0.npz",
    "data/blip_simulation_4/point_cloud_view0_tpc0.npz"
  ]
  classes:        ["source", "shape", "particle"]

loader:
  batch_size:       2
  test_split:       0.0
  test_seed:        100
  validation_split: 0.2
  validation_seed:  100
  num_workers:      4

training:
  epochs:       2
  checkpoint:   10
  progress_bar: 'all'   # train, validation, test, all
  rewrite_bar:  False   # wether to leave bars after each epoch
  save_predictions: True  # wether to save network outputs in original file
  no_timing:  False     # wether to keep timing/memory info in callback
  gpu:        True
  gpu_device: 0
  seed:       42

model:
  model_type:   "PointNet++"
  set_abstraction_layers:
    sampling_methods:       ["farthest_point", "farthest_point"]
    sampling_num_samples:   [32, 16]
    grouping_methods:       ["query_ball_point", "query_ball_point"]
    grouping_type:          ["multi-scale", "multi-scale"]
    grouping_radii:         [[2, 4, 8], [2, 4, 8]]
    grouping_samples:       [[16, 32, 128], [16, 32, 128]]
    pointnet_embedding_type:        ["dynamic_edge_conv", "dynamic_edge_conv"]
    pointnet_embedding_mlp_layers:  [[2,2],[2,2]]
    pointnet_number_of_neighbors:   [20, 20]
    pointnet_aggregation:           ["max", "max"]
    pointnet_input_dimension:       [3, 9]
  feature_propagation_layers:
    # need to add pointnets to these interpolations
  segmentation_layer:
    # number of inputs is original coordinates + embeddings
    num_inputs:   15
    mlp_layers:   [32, 64, 128]
    classifications:  ["source", "shape", "particle"]
    number_of_classes: [8, 7, 32]
  classification_layers:

criterion:
  multiclass_nll_loss:
    alpha:  1.0
    
metrics:
  confusion_matrix:
    inputs: ["source", "shape", "particle"]
    number_of_classes: [8, 7, 32]

callbacks:
  loss:
  confusion_matrix:
    sig_acceptance: [0.1, 0.5, 0.9]

optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9